### ISSUE TITLE
llvmlite.binding.TargetMachine.emit_object() creates incorrect executable type on Windows

### ISSUE THREAD

**Issue by Heasummn** [numba/llvmlite#181]
I was messing around and trying to create an executable using llvmlite on my Windows machine, but I couldn't get it to work. I noticed that even though all of the default settings told me that the executable would be of the COFF format, it was an ELF executable. Here's an example shell run showing the issue: https://gist.github.com/Heasummn/3776762309337b7c3326d0fc26c3ae65 . This generated file cannot be run by Windows. 

I'm running Windows 10, the beta that allows Bash on Windows, and Python 3.5 in a Conda Virtual Environment. I'm using the latest llvmlite version available on Conda.

**Comment by whitequark** [comment]
In this case not the triple from the target machine is used, but the triple from the module. Specify that correctly, and it will emit a COFF file:
```
$ python3.5
Python 3.5.2+ (default, Aug  5 2016, 08:07:14) 
[GCC 6.1.1 20160724] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from llvmlite import binding as llvm
>>> llvm.initialize()
>>> llvm.initialize_native_asmprinter()
>>> llvm.initialize_native_target()
>>> target = llvm.Target.from_triple("x86_64-pc-windows-msvc")
>>> target_machine = target.create_target_machine()
>>> mod = llvm.parse_assembly('target triple = "x86_64-pc-windows-msvc"')
>>> object = open("test.obj", "wb")   
>>> object.write(target_machine.emit_object(mod))
252
>>> object.close()
>>> 
$ objdump -a test.obj 

test.obj:     file format pe-x86-64
test.obj
```

Note that, unlike the extension `.exe` that you have used, the file is not an executable. You will need a separate linking step to produce one.

**Comment by thebusytypist** [comment]
@whitequark I am afraid I cannot confirm your solution works on Windows.

If you create target machine with the default configuration on Windows
```
target_machine = target.create_target_machine()
```
It would still create one with ELF format output.

You can check this by:
```
target_machine.triple
```
It will print `x86_64-pc-windows-msvc-elf`, which is incorrect.

The reason is stated in this commit:
https://github.com/numba/llvmlite/commit/7e80b3397b5e9374daf174b62ed128024f527f59

Generally, it will append "elf" tag to the triple if you are on Windows and using the code model `jitdefault`(which is default in `create_target_machine`).

My solution is to tell the `create_target_matchine` to use a different code model for object code generation.
For example:
```
target_machine = target.create_target_machine(codemodel='default')
```

--------------------
llvmlite version: 0.14.0
`llvmlite.binding.llvm_version_info`: (3, 8, 1)

**Comment by whitequark** [comment]
@thebusytypist Oh, thanks for the correction!

**Comment by pitrou** [comment]
> Generally, it will append "elf" tag to the triple if you are on Windows and using the code model jitdefault(which is default in create_target_machine).

Yes, MCJIT on Windows doesn't support COFF objects, only ELF objects. Changing the codemodel as you did is the right solution if you want to generate on-disk COFF files.

**Comment by pitrou** [comment]
I don't think there's anything we can fix here, it's an LLVM limitation. @thebusytypist, thoughts?

**Comment by thebusytypist** [comment]
@pitrou I agree with you. Nothing needs to be fixed in llvmlite. It is just a workaround to generate on-disk COFF files.

**Comment by pitrou** [comment]
Thank you. I'm closing this issue then.
