### ISSUE TITLE
"Extra" dependency

### ISSUE THREAD

**Issue by danilobellini** [numba/llvmlite#35]
Calling `python setup.py install` on the v0.2.1 tag version (9f60cd1), I've got the message (and some "cascading" error messages afterwards):

```
/usr/bin/ld: cannot find -ledit
```

That appears because the `llvm-config --system-libs --libs all` included that `-ledit`. That might be an Ubuntu 14.10 (utopic) LLVM  packaging issue, but I'm not sure whether `llvm-3.5-dev` should have `libedit` as dependency. Anyway, including in the README that [some] people should install `libedit-dev` would help at least as a workaround.

**Comment by eliben** [comment]
I encountered this problem as well and mentioned it in the short blog post I wrote about installing and using llvmlite [http://eli.thegreenplace.net/2015/building-and-using-llvmlite-a-basic-example/]

LLVM gained the dependency on libedit just last year [with https://github.com/llvm-mirror/llvm/commit/cb6684b63b3c4c5a90e194c5719bc82690180f30] for the sake of the clang-query tool. It was placed in the core of LLVM because it can have additional users like LLDB.

**Comment by pitrou** [comment]
A mention was added in the README in PR #37.
