### ISSUE TITLE
(new) Warning at shutdown

### ISSUE THREAD

**Issue by dscole** [numba/llvmlite#350]
Getting the following warning at shutdown with llvmlite-0.23.0 and numba-0.38.0:

```
Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x7fdf4a8f46d0>>
```
Not sure how to track it down further.

**Comment by asmeurer** [comment]
I get a similar warning, in Python 2 only

```
Exception TypeError: "'NoneType' object is not callable" in <bound method ExecutionEngine.__del__ of <llvmlite.binding.executionengine.ExecutionEngine object at 0x11d2b2390>> ignored
```

(you can reproduce this by running the [sympy](http://github.com/sympy/sympy) llvm tests, `./bin/test llvm`)

The `__del__` method is https://github.com/numba/llvmlite/blob/44a515a346d420ee999e329960d50f6768551dd5/llvmlite/binding/ffi.py#L241-L242

I'm not really clear on [`__del__`](https://docs.python.org/2/reference/datamodel.html#object.__del__) documentation if you're supposed to be able to fix this by making something start with an underscore. Or should it just be guarded with a check if it's `None`? 

I also don't know why it's Python 2-only. I guess the del algorithm changed in Python 3 so that `close` doesn't get deleted when `__del__` is called.

**Comment by asmeurer** [comment]
Guarding against None removes the warnings for me. https://github.com/numba/llvmlite/pull/368

**Comment by will133** [comment]
The guard against the close does not seem to work for me.  I dug into it a little bit and the problem at least for me has to do with the _dispose function in:

https://github.com/numba/llvmlite/blob/80d8f86ff81467a52658df95e58a4524bfbf5403/llvmlite/binding/module.py#L77-L78

The LLVMPY_DisposeModule function seems to raise the "NoneType is not callable exception" error internally during exit on python 2.7.  If i do the following:

```python
    def _dispose(self):
        try:
            self._capi.LLVMPY_DisposeModule(self)
        except TypeError as e:
            if 'object is not callable' in str(e):
                pass
            else:
                raise
```
I can get rid of the error.  Do you know if that's the right thing to do?  Or if there's something wrong going underneath the DisposeModule call?

This issue is also reported on the numba bug (https://github.com/numba/numba/issues/2818) where it can be reproduced by doing (from @stuz5000):

```python
import numba
import numpy as np


@numba.jit
def f(a):
    return np.asarray(a)


if __name__ == "__main__":
    f([1, 2, 3, 4])
```

I'm using numba=0.40, llvmlite=0.25.0, python=2.7.15 on Linux from conda-forge.

**Comment by stuartarchibald** [comment]
I think the root cause is that prior to Python 3.4 the shutdown sequence would set some things (esp. globals and modules) to None to help the gc. Given llvmlite already has a method for detecting that Python is shutting down it can be reused here.

Patch to fix in https://github.com/numba/llvmlite/pull/403.

**Comment by jvesely** [comment]
Hi,
our project (https://github.com/PrincetonUniversity/PsyNeuLink) uses llvmlite directly and we still see this problem on python 3.5. It has been reproduced in these configurations:
python: 3.5.6, llvmlite: 0.24.0, os: windows 10
python: 3.5.2, llvmlite: 0.25.0, os: macos 10.12.6
￼￼￼￼python: 3.5.3, llvmlite: 0.25.0, os: macos 10.11.6

**Comment by stuartarchibald** [comment]
@jvesely Thanks for the report. A patch is queued for review here: https://github.com/numba/llvmlite/pull/403 hopefully this will fix it.
