### ISSUE TITLE
A question about calling back into python 

### ISSUE THREAD

**Issue by jiamo** [numba/llvmlite#364]
I use llvmlite (0.12.1) to run func like this:

    from ctypes import CFUNCTYPE, c_double, c_int64, POINTER
    return_type = POINTER(c_int64)
    fptr = CFUNCTYPE(return_type)(ee.get_pointer_to_function(func)  # func is main func name which already jit the coe
   result = fptr(*args)

But I always got content like this

    (Pdb) c_void_p.from_buffer(ret.contents).value
    140732764985632

Not the right and small value (the pointer pointed to). For detail you can see https://github.com/jiamo/pcc/blob/master/tests/test_main_return_ptr.py

So how can I make CFUNCTYPE work correct with a function return pointer?

**Comment by alendit** [comment]
In the linked test case, you allocate an int pointer on stack and then return it's address. This doesn't work in C either, since after returning the function discards the content of it's stack frame. It might work by chance sometimes, but it's an undefined behaviour. 

If you really want to return a pointer, you'd have to allocate it on heap with `malloc(sizeof(int))` and return that address. Just don't forget to `free` it after you're done with it.

**Comment by jiamo** [comment]
I see. At now I can't use `malloc` in the C code. It is just a small project to parser C code. So the complex library was not supported. I change the local var to global var (have update the test code). This time I got segmentation fault . Seem like the python host env can't access the global address in native code generated by llvmlite. Or Is there possible to `alloc`  a var in heap by llvmlite itself?

**Comment by alendit** [comment]
The execution engine is created within the context [here|https://github.com/jiamo/pcc/blob/master/pcc/evaluater/c_evaluator.py#L60] and is destroyed when the function returns, so when you try to access the variable outside of this function, the memory you are pointing to is already deallocated and you get a segfault. You can load the contents of the pointer somewhere after the line 77 and return it, or you can keep the ExecutionEngine around for longer.

In general try to make sure the problem is really in the library code and not in your user code. The best way to do it, is to create a minimal working example which demonstrates the problem.

**Comment by jiamo** [comment]
Thanks. I got my result.  make the context live longer.
