### ISSUE TITLE
Move to LLVM 7

### ISSUE THREAD

**Issue by seibert** [numba/llvmlite#396]
LLVM 7.0.0 has been tagged and should be posted any day now.

**Comment by iosonofabio** [comment]
Hi guys,
sorry I'm a bit confused by the relationship between this repo and the cmsdist reference. Is there any plan to get numba/llvmlite to support LLVM7?
Thank you

**Comment by fwyzard** [comment]
Hi Fabio,
we currently do not have plans to work on llvmlite itself, at least as far as I know.

cmssw uses both llvm/clang and llvmlite/numba; I am pushing to adopt llvm 7, but before we can can switch the production branch we need llvmlite to support it as well; I added a reference to this issue so our release managers could track the developments here :-)

Sorry for the confusion,
.Andrea

**Comment by seibert** [comment]
As an update: This should be coming sooner now that the LLVM patches we rely on have been ported to LLVM 7 successfully.

**Comment by seibert** [comment]
(also, as a former particle physicist, I'd love to know what CMS does with Numba...)

**Comment by amit112amit** [comment]
Arch Linux ( and Antergos ) have moved to llvm 7.0. Kindly update the 'python-llvmlite' AUR package when this is done.

**Comment by stuartarchibald** [comment]
Reminder to add support for `perf` event listeners following https://github.com/numba/llvmlite/pull/394.

**Comment by stuartarchibald** [comment]
PRs so far:
* Move to LLVM 7 https://github.com/numba/llvmlite/pull/404 [Merged]
* Throttle parallel make thread count on armv7l https://github.com/numba/llvmlite/pull/407 [Merged]
* Native cmake for armv7l https://github.com/numba/llvmlite/pull/409 [Merged]
* Re-enable SVML (bug prevented it being detected on initial move to llvm 7) https://github.com/numba/llvmlite/pull/408 [Merged]
* Disable SVML again in https://github.com/numba/llvmlite/pull/410 due to https://github.com/conda-forge/llvmdev-feedstock/issues/52

Numba PR for update to LLVM 7: https://github.com/numba/numba/pull/3437

**Comment by handicraftsman** [comment]
Yeah, moving to llvm 7 would be nice - llvm 7 is available under `llvm` name in archlinux repositories, and it conflicts with `llvm6` package

**Comment by seibert** [comment]
note that due to some test failures with the new LLVM (upgrading LLVM always seems to break something) we've backed out our LLVM 7 patches while we continue to work on the issue.  We're still hoping for the release at the end of November to be based on LLVM 7.

**Comment by seibert** [comment]
Closing as this was completed a while ago.
