### ISSUE TITLE
llvmlite 0.27.1 not available through `pip install`

### ISSUE THREAD

**Issue by atzannes** [numba/llvmlite#459]
I can see `llvmlite 0.27.1` [on pypi](https://pypi.org/project/llvmlite/0.27.1/#history), but when I try to install it with `pip intall llvmlite==0.27.1`, I get the error saying the version is not available. I can see that the package is missing from the [pypi simple index](https://pypi.org/simple/llvmlite/). 

The reason this is annoying, is because I use `pipenv` which updated my dependency to `llvmlite=0.27.1`, and so I now have to pin that transitive dependency to get by build going. I don't know enough about, pypi, pipenv, and the pypi release process to know which of these three parties need to fix something, so I thought I'd start by asking here.

**Comment by seibert** [comment]
Ah, so I think I can explain what happened:

There was a packaging issue with the macOS llvmlite 0.27.0 wheel that was reported.  Since PyPI will not allow existing files to be replaced, we had to bump the version number (to 0.27.1) in order to upload a new package.  Because there were no actual source changes, we did not build and upload 0.27.1 wheels for the other platforms.  `pip` will automatically figure out the latest version for the current platform, so we assumed that would be fine.  If `pipenv` is determining the latest version without checking the platform, then it would conclude the most recent version is 0.27.1, even though wheels do not exist for Linux or Windows (which I assume you are using).

This is probably an issue that should be resolved with pipenv, but it is also true that not having the same version number for all platforms can be confusing, and is something we should avoid.

Thanks for letting us know about the problem, and we'll look to post updated wheels for all platforms.

**Comment by atzannes** [comment]
Thanks for the awesomely informative reply @seibert . I'll follow up with `pipenv`

**Comment by atzannes** [comment]
[Here's the pipenv issue](https://github.com/pypa/pipenv/issues/3511) I opened

**Comment by atzannes** [comment]
The linux wheels are now available, so I guess we can close this issue

**Comment by seibert** [comment]
In the future, we'll make sure to use the `--build-number` flag to make replacement wheels when there are packaging issues so we don't ever do this again.  :)
