### ISSUE TITLE
Missing version 0.28.0 on Pypi

### ISSUE THREAD

**Issue by marcelotrevisani** [numba/llvmlite#472]
Hey guys,

Could someone please add the version ``0.28.0`` to the pypi?

**Comment by marcelotrevisani** [comment]
cc: @ilanschnell

**Comment by seibert** [comment]
Hi, you've caught us in the middle of our release process for Numba and llvmlite.  (We tagged 0.28.0 yesterday)  Due to the number of configurations and testing, it takes us a day or two to get everything built.  You should see things appear on PyPI later today.

(also, Ilan doesn't work on this project.)

**Comment by marcelotrevisani** [comment]
Hi @seibert thanks for the feedback!
:)

**Comment by Juanlu001** [comment]
PSA: To protect your CI from breaking in these circumstances,

```
export PIP_PREFER_BINARY=true
```

(pip >= 18.0)

**Comment by marcelotrevisani** [comment]
@Juanlu001 thanks for your message, but I am trying to create a new package for ``numba`` in ``conda-forge`` and it depends on ``llvmlite 0.28.0``. Because of that I was trying to create a package for ``llvmlite 0.28.0``, I can't get the source code from tarballs because the ``sha256`` is always changing.
And in ``PyPi`` there is no source code for ``0.28.0`` that is why I was requesting it! :)
