### ISSUE TITLE
What is the minimum requirement for LLVM required by llvmlite ?

### ISSUE THREAD

**Issue by samfux84** [numba/llvmlite#473]
LLVM contains the parts:

- LLVM
- Clang
- compiler-rt
- libc++
- libc++abi
- libunwind
- LLD
- LLDB
- OpenMP
- Polly
- clang-tools-extra

What is the minimum requirement for getting a working llvmlite ?

Is building LLVM and Clang sufficient or are more parts required ?

**Comment by seibert** [comment]
The install guide has some more information:

https://llvmlite.readthedocs.io/en/v0.28.0/admin-guide/install.html

Due to churn in the LLVM interfaces (and bugs we have to work around), a given llvmlite version is intended for only one major release of LLVM.  llvmlite 0.27 and 0.28 (released yesterday) require LLVM 7.x.

However, looking at the install guide, we failed to update it when support for LLD was added to llvmlite in a recent release.  I think we now need both LLVM and LLD to be present, but none of the other packages you list.  (We don't use clang for anything, for example.)

**Comment by samfux84** [comment]
@seibert : Thank you very much for your reply.

I was trying to build LLVM 7.0.1 on CentOS 7.5 with GCC 4.8.2. First I tried to build all components of LLVM with GCC 4.8.2 (according to the documentation of LLVM 7.0.1, this should be possible). I noticed that many components can actually not be built with GCC 4.8.2 due to internal compiler errors. Instead of changing the minimal GCC in the requirements part of the documentation, people were told to just use GCC 6 to fix this problem.

I could now successfully build LLVM+clang+compiler-rt+openmp with GCC 4.8.2 and using this, I could successfully build llvmlite 0.28.0.

Again, thank you for answering my question.

Best regards

Sam
