### ISSUE TITLE
Officially support llvm 10

### ISSUE THREAD

**Issue by KOLANICH** [numba/llvmlite#507]
I have installed llvm10 from its apt repo, set it to be used by default with update_alternatives, done some trivial patches to make it work with llvm 10 and run the tests. The tests have passed (with exception of tests testing llvm version), the tests of numba have passed and the tests of a lib using numba have passed. I feel like the project should support llvm 10 officially.

**Comment by KOLANICH** [comment]
>We should look into making it easier to disable the LLVM version check for people who want to run other versions and accept that we haven't tested them.

Version checks are not only fixes I have to do. They got rid of `llvm::make_unique` in favour of `std::make_unique` so this should be selected via a macrodef.

And tests should be a bit smarter rather than a check of a hash.

**Comment by jakirkham** [comment]
Just an FYI LLVM 10 is out now.

**Comment by flying-sheep** [comment]
Aaand already in Arch Linux’ repos. As someone who has to regularly do a manual intervention because some LLVM update breaks llvmlite, I wonder what could be done to prevent long delays in the future: Could something be more automated or is there just too much non-automatable manual work for the number of knowledgable volunteers? Is the test coverage too low and too many manual tests have to be done? Or was 8→9 an update with uncharacteristically many architectural changes?

**Comment by pwuertz** [comment]
Just tried @KOLANICH llvm-10 fix branch, `llvm::unwrap` caused the build to fail though:
```
transforms.cpp: In function ‘unsigned int LLVMPY_PassManagerBuilderGetOptLevel(LLVMPassManagerBuilderRef)’:
transforms.cpp:32:43: error: ‘unwrap’ is not a member of ‘llvm’
   32 |     llvm::PassManagerBuilder *pmb = llvm::unwrap(PMB);
```

**Comment by abebeos** [comment]
@esc, can be closed.

https://github.com/numba/llvmlite/pull/599

**Comment by esc** [comment]
@abebeos thanks for the ping and @KOLANICH thanks for closing.
