### ISSUE TITLE
a bug in build.py??

### ISSUE THREAD

**Issue by ddeeppnneett** [numba/llvmlite#530]
Hi, 

I am an  archlinux user.  And I think I get a bug in build.py.  

```
    if not (out.startswith('8.0.') or out.startswith('7.0.') 
            or out.startswith('7.1.')):
        msg = (
            "Building llvmlite requires LLVM 7.0+ Be sure to "
            "set LLVM_CONFIG to the right executable path.\n"
            "Read the documentation at http://llvmlite.pydata.org/ for more "
            "information about building llvmlite.\n"
            )
        raise RuntimeError(msg)
```

But the version of llvm  in the archlinux is 

> extra/llvm 9.0.0-4 [installed]

Maybe  < or out.startswith('9.0.')> is needed  there inorder for the new verions of llvm.  Or  another smart way.

**Comment by seibert** [comment]
We haven't added LLVM 9.0 because we haven't verified support for it yet.  In the past we've had issues with new LLVM releases frequently breaking things, so we do a version check and then move forward to the next LLVM release when it has been tested.

The current scenario is actually a little unusual because we normally only support one major release  at a time.  We're currently split between two major releases because LLVM 8.0 has some severe PPC bugs for JIT usage, but (thankfully) the API is close enough between 8.x and 7.x for us to maintain support for both.

LLVM 9.0 is on our todo list, but I don't have an immediate ETA.

**Comment by ddeeppnneett** [comment]
OK, I see. Then I will try to downgrade the version of llvm. 

Thanks.
