### ISSUE TITLE
Support LLVM 15

### ISSUE THREAD

**Issue by MehdiChinoune** [numba/llvmlite#897]
---

## Feature request
llvmlite couldn't be built against LLVM 15 even after applying patch from #830 , Please consider supporting LLVM-15. We need that so we could package llvmlite+numba for MSYS2 which is a rolling platform and we couldn't have two LLVM versions be installed at the same time.

**Comment by gmarkall** [comment]
LLVM 15 (or maybe a later version) will be considered once we have finished support for LLVM 14. In the meantime, you may be able to work up a local patch with some inspiration from this commit: https://github.com/gmarkall/llvmlite/commit/5bdfb9ccf089fc18a9f8db5d2ffac1692533f7cd - however, I don't know whether there will be more subtle issues than it just not building.

Some of the passes seem to have been renamed or removed - in that commit I just commented out code to use them, but you may be able to find something better to do than I did when working on that commit. Note that some of the changes I made were to skip tests on RISC-V, but it may have been that some of those tests also fail on  non-RISC-V platforms with LLVM 15.

**Comment by gmarkall** [comment]
Note, I edited the title to make it clear this issue is about LLVM 15 (as opposed to some other version) support.

**Comment by esc** [comment]
@MehdiChinoune may I ask, why was this closed? I think we should keep this open as we wish to move to LLVM 15 at some stage.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune may I ask, why was this closed? I think we should keep this open as we wish to move to LLVM 15 at some stage.

I am a contributor of MSYS2 which is a rolling-based package manager. LLVM 16 will be released soon so we will have to rebuil llvmite gainst it. Considering the current status of llvmlite not supporting LLVM>11 It' s unlikely to see any support of LLVM 16 in the near future.
I am not going to open a new issue for every new release.

**Comment by esc** [comment]
@MehdiChinoune thank you for your response. I would like to bring to your attention that I discourage you from shipping an llvmlite that is compiled against any LLVM version that has not been approved by the Numba/llvmlite maintainers. The reason is that LLVM major versions are historically not backwards compatible and it usually takes between 3-6 months of full time work to fully debug and implement support for new LLVM major versions. This is compounded by the necessity to support the matrix of multiple different operating systems and multiple different hardware architectures.   While it's easy enough to prepare patches to allow it to compile successfully, we commonly see multiple runtime errors that are usually confusing and hard to debug. This means that you may compromise your user experience leading to unexpected segfaults in the best case and incorrect numerical results (silent errors) in the worst case. The problem with this may be, that your users report bugs against the Numba/llvmlite issue trackers, which in turn cause headaches, issues and wasted time for the maintainers.

We recently had a case where a specific distributor (conda-forge) unfortunately failed to include a specific LLVM patch that Numba/llvmlite needs to operate correctly on `arm64`. The issue surfaced on the Numba tracker but none of the maintainers was able to reproduce the bug. After going round and round in circles for several weeks with multiple people involved, we finally identified the issue through exhaustion of all possible causes. Needless to say, many of us wasted time here that could have been spent doing more productive work -- for example LLVM 14 support. 

We have an FAQ entry about this here: https://llvmlite.readthedocs.io/en/latest/faqs.html#why-doesn-t-llvmlite-always-support-the-latest-release-s-of-llvm 

Wer also recentlyu encountered more issues related to LLVM 14 stability that have been summarized here, in case you want to know more about our work to support LLVM 14: https://github.com/numba/numba/issues/8738

If your distribution system and package manager are unable to support multiple concurrent versions of LLVM, it may not be a good idea to distribute Numba and llvmlite as part of it. Whether you do is up to you, but please be aware that doing so may create significant risk for your users and the Numba and llvmlite ecosystem as a whole.
