### ISSUE TITLE
Release llvmlite >= 0.41.0 via pip?

### ISSUE THREAD

**Issue by rachtsingh** [numba/llvmlite#974]
Installing llvmlite via pip only installs v0.40.1:

```bash
pip install --upgrade llvmlite
...
  Downloading llvmlite-0.40.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
...
```

This would normally not be much of an issue, but the latest numba (0.58.0) requires `llvmlite >= 0.41.0dev0`, and the latest numba is the only one that supports numpy 1.25. So to upgrade numpy to 1.25, we would need to build llvmlite from scratch, which is somewhat daunting.

**Comment by esc** [comment]
@rachtsingh thank you for asking about this. When building `main` branches of Numba and llvmlite these end up being versioned with the first reachable tag using `versioneer` and `git describe`. Currently these are `0.58.0dev0` and `0.41.0dev0` respectively. This means, that neither 0.58.0 and 0.41.0 are actually released so there are consequently no artifacts available on PyPi. We do however build development releases (nightlies) and upload them to anaconda.org so that they can be installed using `conda` from the `numba/label/dev` channel. You can install a development release of Numba and llvmlite using:

```
$ conda create -n test-nightlies python=3.11
...
$ conda activate test-nightlies
...
$ conda install -c numba/label/dev numba
...
```

Will install:

```
  llvmlite           numba/label/dev/osx-arm64::llvmlite-0.41.0dev0-py311_76
  numba              numba/label/dev/osx-arm64::numba-0.58.0dev0-np1.22py3.11h8833779_g5ef7c86f7_419
```

We do plan to build "nightlies" to PyPi too at some point but that work is currently not scheduled, so please use `conda` to install those.

Regarding NumPy 1.25 support, the work to support this version has been completed and merged to `main`:

https://github.com/numba/numba/pull/9105

We are planning to release new versions of Numb and llvmlite soon (Current estimate is to tag a release candidate the week starting 14th of August, but that is an "estimate"). The milestones are here:

* https://github.com/numba/numba/milestone/69
* https://github.com/numba/llvmlite/milestone/19

and we will be opening release checklists this week to get the release process going. Keep an eye on the issue tracker if you are interested.

**Comment by rachtsingh** [comment]
Thank you for the detailed response and for specifying your release policy, it is very much appreciated. I'll keep an eye out!

**Comment by esc** [comment]
@rachtsingh no problem.

FYI: release checklists are out now:

https://github.com/numba/llvmlite/issues/977

https://github.com/numba/numba/issues/9122
